### ISSUE TITLE
Overview dashboard not adding metrics for sql datasource

### ISSUE THREAD

**Issue by dlopes7** [dynatrace-extensions/dynatrace-extensions-copilot#41]
The `Dynatrace: Create overview dashboard` command does not add metrics for sqlMySql datasources.

I suspect this is because the datasource type is `sqlMySql` instead of `sql`, and this should be happening for other sql datasource as well.
So the code that tries to find metrics cannot find them inside the `sqlMySql` yaml element.

Steps to reproduce:

Create an `extension.yaml` with this content and hit the `Create overview dashboard` command

```yaml
sqlMySql:
  - group: Global Status
    query: |
      SELECT EVENT_NAME, COUNT_STAR
      FROM performance_schema.events_statements_summary_global_by_event_name
      WHERE EVENT_NAME IN (
                          'statement/sql/select', 
                          'statement/sql/insert', 
                          'statement/sql/update', 
                          'statement/sql/delete' 
                          )
    metrics:
      - key: mysql.statements.count
        value: col:count_star
        type: Count
    dimensions:
      - key: statement_type
        value: col:event_name
metrics:
  - key: mysql.statements.count
    metadata:
      displayName: Statements
      description: The number of statements executed for each type (select, insert, update, etc)
      unit: Count
      dimensions:
        - key: statement_type
          displayName: Statement Type
      tags:
        - mysql
topology:
  types:
    - name: mysql:instance
      displayName: MySQL Instance
      rules:
        - idPattern: mysql_instance_{device}
          instanceNamePattern: MySQL @ {device}
          iconPattern: database
          sources:
            - sourceType: Metrics
              condition: $prefix(mysql.)
```

What happens: the dashboard is generated but no metrics are added.  
What is expected: The metric `mysql.statements.count` is added to the dashboard.
