### ISSUE TITLE
Feature - Automate Metric Metadata Section

### ISSUE THREAD

**Issue by damass** [dynatrace-extensions/dynatrace-extensions-copilot#77]
**Summary**
Parse YAML from DataSource section (snmp, prometheus, wmi, etc) to create basic metrics metadata section.

**Details**
Find all metric keys that are defined in the extension's datasource section (if any) and create metric metadata section with basic structure. 

**Use Cases**
Speed up creation of metadata section along with ensuring no metric keys are missed. 

**Challenges**
Users will still need to validate/modify the metadata but gives a head start. 
Currently not sure how this will work with the current Prometheus code action for adding metadata along with how to support generic approach but also allowing for datasource specific implementations -> https://github.com/dynatrace-extensions/dynatrace-extensions-copilot/issues/66

**Comment by damass** [comment]
My first thought was to create a Command Pallette Command that asks a few questions (some answers could be pre-populated) such as datasource, metric prefix, metric separator/format (dots, dashes, camelCase) that then adds in the basic skeleton of the metrics section. From there either integrate the other code actions automatically or leave them to be manually triggered. 

I have this python script that does something similar but the idea would be make it more generic for any datasource : 

[create_metric_metadata.py.txt](https://github.com/dynatrace-extensions/dynatrace-extensions-copilot/files/10872201/create_metric_metadata.py.txt)

**Comment by radu-stefan-dt** [comment]
Ok. If you do need to collect any input from the user, then Command is definitely the way to go.
Before you start any proper integration with the Copilot, could you flesh out (just some bullet points / pseudo code) the workflow and maybe provide some sample expected output?

We'll have to work in some way with the other CodeAction Providers too (Prometheus, Snmp, etc.), so having an idea of how this will operate will be helpful. Might be that they check if metadata is present already and only fill in the missing metrics (or even just the missing details for the existing metrics). Might be that your Command will have to check what's already there and give an "overwrite" warning. Something like that.

**Comment by damass** [comment]
What I'm thinking would be using the yaml at the end of the comment. We could also use this to enforce some metric key naming best practices. 

1. Invoke Command Palette `Dynatrace: Create Metric Metadata `
2. Answer Question : Create Metric Metadata for which Datasource? Autopopulate with `sqlMySql `
2.a - If `prometheus` maybe end process and suggest existing code action? 
2.b. Scrape all metric keys from YAML for that section 
4. Answer Question : What is your metric prefix? Autopopulate with common part of metric prefix (if able to find any). In this case it would be `mysql`
5. Answer Question : What is your metric key format? Select from dropdown (or Autopopulate) : dots, dashes, camelCase. In this case it would be "dots". 
6. Goes through list of scraped keys (from step 2.a) and create yaml similar to this below. Could also include more (optional) properties for the metadata best practices (IE tags, souceEntityType, min/max (if key contains percent/percentage), etc...). 
-----------------------------------
``` yaml
metrics:
  - key: mysql.global_status.queries.count
    metadata:
      # dimensions:  # if any dimensions are associated with that key at group/subgroup level 
      #   - key: dimension.1 
      #     value: Dimension 1
      displayName: global_status Queries
      unit: Unspecified
      description: ''
  - key: mysql.global_status.slow_queries.count
    metadata:
      displayName: global_status Slow Queries
      unit: Unspecified
      description: ''
```
-----------------------------------
``` yaml
sqlMySql:
  - group: Global Status Table
    featureSet: global_status
    query: |
      SELECT
          sum( if( VARIABLE_NAME = 'Queries', VARIABLE_VALUE, 0))  AS queries,
          sum( if( VARIABLE_NAME = 'Slow_queries', VARIABLE_VALUE, 0))  AS slow_queries
      FROM performance_schema.global_status
    metrics:
      - key: mysql.global_status.queries.count
        value: col:queries
        type: count
      - key: mysql.global_status.slow_queries.count
        value: col:slow_queries
        type: count
```
